version: "3.8"

services:
  php:
    image: php:8.2-cli
    container_name: php_dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:8080"
    command: php -S 0.0.0.0:8080
